# Generated by Django 2.2.5 on 2019-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191204_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='todos_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
