# Generated by Django 2.2.5 on 2019-12-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20191217_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='todo_prio_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
